### ISSUE TITLE
Class Naming - Specifying unity

### ISSUE THREAD

**Issue by andrepinho** [filipelinhares/funkcss#2]
The current class naming doesn't have any indication on what css unity is being used.
​
For example, spacing and sizes helpers:
​

``` css
.mT-100 /* 100 is to pixel */
.w-100 /* 100 is to percentage */
```

​
Knowing css has quite a few units:
- `%`
- `rem`
- `em`
- `px`
- `vh`
- `vw`
  ​

**Isn't it a good idea to specify what unit is being used in that class?**
​
Here are a example of what I'm talking about:

``` css
.w-100p {
   width: 100%;
}
​
.fz-1r {
   font-size: 1rem;
}
```

Perhaps pixels could be default, thus not needing a explicit ​indication:

``` css
.pB-20 {
  padding-bottom: 20px
}
```

Here's a table which I think could be a good reference for a naming rule:

| Unity | Class indication | Example |
| --- | --- | --- |
| px | default (none) | .pT-20 |
| rem | r | .fz-2r |
| em | e | .fz-1e |
| % (percentage) | p | .w-100p |

**Any suggestion or comments, please reply this issue.**
Thanks!
