### ISSUE TITLE
Some classes aren't working

### ISSUE THREAD

**Issue by gabeborges** [filipelinhares/funkcss#4]
When applying to links:

``` css
td-n { text-decoration:none; } /* for hover state */
```

Pseudo-classes too:

``` css
.c-green\:h:hover { color: red; }
.c-green\:f:focus { color: red; }
```

**Comment by filipelinhares** [comment]
Hey @cbgabe thanks for the report.

To use `td-n` on hover you need to create a new class `td-n:h` and set a hover pseudo class to it:

``` css
.td-n\:h:hover { text-decoration: none; }
```

When using those classes, don't forget to use `td:h` in the HTML too.
[Example](http://codepen.io/filipelinhares/pen/EgjxaP)
